DROP TABLE restaurants IF EXISTS CASCADE;
DROP TABLE dishes IF EXISTS CASCADE;
DROP TABLE users IF EXISTS CASCADE;
DROP TABLE user_roles IF EXISTS;
DROP SEQUENCE GLOBAL_SEQ IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name             VARCHAR(255)               NOT NULL,
    email            VARCHAR(255)               NOT NULL,
    password         VARCHAR(255)               NOT NULL,
    is_voted         BOOLEAN   DEFAULT FALSE    NOT NULL
);

CREATE UNIQUE INDEX users_unique_email_idx
    ON USERS (email);

CREATE TABLE user_roles
(
    user_id INTEGER NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE restaurants
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name             VARCHAR(255)               NOT NULL,
    votes            INTEGER                    NOT NULL
);

CREATE TABLE dishes
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    desc             VARCHAR(255)               NOT NULL,
    price            INTEGER                    NOT NULL,
    restaurant_id    INTEGER                    NOT NULL,
    FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE
);